/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClientSocket.app;
import ClientSocket.ClientSocket;

public class ClientConnect {
    public static void main(String[] args) {
        try{
            ClientSocket csock = new ClientSocket();
            csock.write("Henlo my Nicky is a dingydong. boop toot");
            // csock.teardown();
        }
        catch (Exception e){
            System.out.println("Found error " + e);
        }
    }
}
